[package]
name = "tcp_transparent_repeater"
version = "0.2.0"
authors = ["Yifan Gao <git@yfgao.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
nix = "0.19"
bytes = "1"
